import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Check, Clock3, Ruler } from "lucide-react";
import { Button } from "@/components/ui/button";
import { images } from "@/config/images";
import { delivery, products, site, fontStyles, sizeHints, formatKz } from "@/config/site";

export const Route=createFileRoute("/produto")({validateSearch:(s:Record<string,unknown>)=>({produto:typeof s.produto==="string"?s.produto:undefined}),head:()=>({meta:[{title:`${site.name} — detalhes da peça`},{name:"description",content:"Detalhes, preços de referência e opções de personalização."}],links:[{rel:"canonical",href:"/produto"}]}),component:ProductPage});

function ProductPage(){
 const {produto}=Route.useSearch(); const product=products.find(p=>p.slug===produto)??products[0];
 return <div className="mx-auto max-w-7xl px-5 py-10 sm:py-14"><Link to="/fios" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-gold"><ArrowLeft className="size-4"/>Voltar ao catálogo</Link><div className="mt-8 grid gap-10 lg:grid-cols-2"><div className="overflow-hidden rounded-2xl border border-border bg-card"><img src={images[product.image]} alt={`${product.name} — pré-visualização da peça`} width="1200" height="1200" className="aspect-square w-full object-cover"/></div><div><p className="eyebrow">{product.category==="mascote"?"Mascote personalizada":"Fio personalizado"}</p><h1 className="mt-2 font-display text-4xl sm:text-5xl">{product.name}</h1><p className="mt-4 text-base leading-7 text-muted-foreground">{product.description}</p><div className="mt-7 rounded-xl border border-gold/20 bg-surface p-5"><p className="text-xs uppercase tracking-widest text-muted-foreground">Preços de referência</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{product.prices.map(p=><div key={p.label} className="rounded-md border border-border bg-background p-3"><span className="text-sm text-muted-foreground">{p.label}</span><strong className="mt-1 block font-display text-2xl text-gold">{formatKz(p.amount)}</strong></div>)}</div><p className="mt-3 text-xs leading-5 text-muted-foreground">O preço final é confirmado pela administração conforme o comprimento do nome e a cor escolhida.</p></div><div className="mt-7 grid gap-3">{product.details.map(d=><div key={d} className="flex gap-3 text-sm text-muted-foreground"><Check className="mt-0.5 size-4 shrink-0 text-gold"/>{d}</div>)}</div><div className="mt-7 grid gap-3 rounded-xl border border-border p-5 sm:grid-cols-3"><div><Clock3 className="size-4 text-gold"/><p className="mt-2 text-xs text-muted-foreground">Prazo</p><p className="text-sm">3 semanas a 1 mês</p></div><div><Ruler className="size-4 text-gold"/><p className="mt-2 text-xs text-muted-foreground">Tamanhos de referência</p><p className="text-sm">{sizeHints.join(" · ")}</p></div><div><span className="text-gold">#</span><p className="mt-2 text-xs text-muted-foreground">Estilos</p><p className="text-sm">{fontStyles.length} referências</p></div></div><Button asChild size="lg" className="mt-7 w-full sm:w-auto"><Link to="/encomendar" search={{produto:product.slug}}>Personalizar esta peça</Link></Button></div></div><section className="mt-16 rounded-2xl border border-border bg-surface p-7 sm:p-9"><p className="eyebrow">Processo</p><h2 className="mt-2 font-display text-3xl">O que acontece depois?</h2><div className="mt-7 grid gap-4 md:grid-cols-4">{delivery.steps.map((s,i)=><div key={s.title} className="rounded-lg border border-border bg-background p-5"><span className="font-display text-2xl text-gold">0{i+1}</span><h3 className="mt-2 text-sm font-medium">{s.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{s.text}</p></div>)}</div></section></div>;
}