import { useMemo, useState } from "react";
import { Check, ChevronLeft, ChevronRight, Eye, MessageCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { colorOptions, fontStyles, products, sizeHints, delivery, site } from "@/config/site";
import { whatsappLink, WHATSAPP_NOT_CONFIGURED } from "@/lib/whatsapp";

const typeOptions=[{value:"fio",label:"Fio personalizado"},{value:"mascote",label:"Mascote personalizada"}] as const;
export function OrderForm({initialProduct}:{initialProduct?:string}){
 const preset=products.find(p=>p.slug===initialProduct); const [step,setStep]=useState(1);
 const [tipo,setTipo]=useState<"fio"|"mascote">(preset?.category==="mascote"?"mascote":"fio"); const [nome1,setNome1]=useState(""); const [nome2,setNome2]=useState(""); const [cor,setCor]=useState(colorOptions[0]); const [tamanho,setTamanho]=useState(""); const [estilo,setEstilo]=useState(""); const [notas,setNotas]=useState(""); const [sent,setSent]=useState(false);
 const selectedFont=fontStyles.find(f=>f.code===estilo.split(" ")[0]);
 const errors={nome1:nome1.trim()?"":"Indica o nome a gravar.",tamanho:/^\d+(\.\d+)?$/.test(tamanho.trim())?"":"Indica o tamanho em centímetros (ex.: 5)."};
 const mensagem=useMemo(()=>{const label=typeOptions.find(t=>t.value===tipo)?.label??tipo;return [`Olá ${site.name}! Quero encomendar uma peça personalizada.`,"",`• Tipo: ${label}`,`• Nome: ${nome1.trim()||"(a indicar)"}`,nome2.trim()?`• Segundo nome: ${nome2.trim()}`:null,`• Cor: ${cor}`,`• Tamanho: ${tamanho.trim()||"(a indicar)"} cm`,estilo?`• Estilo: ${estilo}`:null,notas.trim()?`• Notas: ${notas.trim()}`:null,"", "Gostaria de confirmar o preço final e o prazo de produção. Obrigado!"].filter(Boolean).join("\n")},[tipo,nome1,nome2,cor,tamanho,estilo,notas]);
 const href=whatsappLink(mensagem); const configured=!!href;
 const canNext=step===1?!!nome1.trim():step===2?/^\d+(\.\d+)?$/.test(tamanho.trim()):true;
 return <form className="space-y-7" onSubmit={e=>{e.preventDefault();if(configured){window.open(href!,"_blank","noopener,noreferrer");setSent(true)}}} noValidate>
  <div className="flex items-center gap-2">{[1,2,3].map(n=><div key={n} className={`h-1.5 flex-1 rounded-full ${step>=n?"bg-gold":"bg-border"}`} aria-hidden/> )}</div>
  <div className="flex items-center justify-between text-xs text-muted-foreground"><span>Passo {step} de 3</span><span>{step===1?"Peça e nome":step===2?"Detalhes":"Rever e enviar"}</span></div>

  {step===1&&<div className="space-y-7"><fieldset className="space-y-3"><legend className="eyebrow">1. Tipo de peça</legend><div className="grid grid-cols-2 gap-3">{typeOptions.map(o=><label key={o.value} className={`cursor-pointer rounded-lg border p-4 transition-colors ${tipo===o.value?"border-gold bg-accent text-gold":"border-border hover:border-gold/50"}`}><input className="sr-only" type="radio" name="tipo" checked={tipo===o.value} onChange={()=>setTipo(o.value)}/><span className="font-medium">{o.label}</span><span className="mt-1 block text-xs text-muted-foreground">{o.value==="fio"?"1 nome 6.800 Kz · 2 nomes 12.200 Kz":"1 nome 8.000 Kz · 2 nomes 14.500 Kz"}</span></label>)}</div></fieldset><div className="grid gap-5 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="nome1">Nome a gravar *</Label><Input id="nome1" value={nome1} onChange={e=>setNome1(e.target.value)} placeholder="Ex.: Joana"/></div><div className="space-y-2"><Label htmlFor="nome2">Segundo nome (opcional)</Label><Input id="nome2" value={nome2} onChange={e=>setNome2(e.target.value)} placeholder="Ex.: Miguel"/></div></div></div>}

  {step===2&&<div className="space-y-7"><div className="grid gap-5 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="cor">Cor desejada</Label><select id="cor" value={cor} onChange={e=>setCor(e.target.value)} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{colorOptions.map(c=><option key={c}>{c}</option>)}</select></div><div className="space-y-2"><Label htmlFor="tamanho">Tamanho em cm *</Label><Input id="tamanho" inputMode="decimal" value={tamanho} onChange={e=>setTamanho(e.target.value)} placeholder="Ex.: 5"/><p className="text-xs text-muted-foreground">Referências: {sizeHints.join(" · ")}</p></div></div><fieldset className="space-y-3"><legend className="eyebrow">Estilo de letra</legend><div className="grid gap-3 sm:grid-cols-2">{fontStyles.map(f=><label key={f.code} className={`cursor-pointer rounded-lg border p-4 ${estilo===`${f.code} ${f.name}`?"border-gold bg-accent":"border-border hover:border-gold/50"}`}><input className="sr-only" type="radio" name="estilo" value={`${f.code} ${f.name}`} checked={estilo===`${f.code} ${f.name}`} onChange={e=>setEstilo(e.target.value)}/><div className="flex items-center justify-between gap-3"><span className="text-sm">{f.code} · {f.name}</span><span className="text-2xl text-gold-soft" style={{fontFamily:f.previewFamily,fontStyle:f.previewStyle}}>{nome1||"Nome"}</span></div><p className="mt-2 text-xs text-muted-foreground">{f.description}</p></label>)}</div></fieldset><div className="space-y-2"><Label htmlFor="notas">Notas (opcional)</Label><Textarea id="notas" value={notas} onChange={e=>setNotas(e.target.value)} rows={3} placeholder="Indica detalhes que a administração deve saber."/></div></div>}

  {step===3&&<div className="space-y-6"><div className="rounded-xl border border-gold/20 bg-surface p-6"><div className="flex items-center gap-2 text-sm text-gold"><Eye className="size-4"/>Pré-visualização digital</div><p className="mt-5 text-center font-display text-5xl text-gold" style={selectedFont?{fontFamily:selectedFont.previewFamily,fontStyle:selectedFont.previewStyle}:undefined}>{nome1||"O teu nome"}</p>{nome2&&<p className="mt-2 text-center text-sm text-muted-foreground">Segundo nome: {nome2}</p>}<p className="mt-4 text-center text-xs text-muted-foreground">Simulação tipográfica. A peça final será confirmada pela administração.</p></div><div className="rounded-xl border border-border bg-card p-5"><h3 className="eyebrow">Resumo do pedido</h3><pre className="mt-3 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{mensagem}</pre></div>{!configured&&<div role="status" className="rounded-md border border-dashed border-border p-4 text-sm text-muted-foreground">{WHATSAPP_NOT_CONFIGURED}. O resumo acima pode ser copiado e enviado pelos canais do negócio.</div>}{sent&&<div role="status" className="rounded-md border border-gold/30 bg-accent p-4 text-sm text-gold">Mensagem aberta para envio. A confirmação do preço e do prazo será feita pela administração.</div>}</div>}

  <div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-between"><Button type="button" variant="outline" disabled={step===1} onClick={()=>setStep(s=>Math.max(1,s-1))}><ChevronLeft className="size-4"/>Voltar</Button>{step<3?<Button type="button" disabled={!canNext} onClick={()=>setStep(s=>s+1)}>Continuar<ChevronRight className="size-4"/></Button>:configured?<Button type="submit"><MessageCircle className="size-4"/>Enviar pelo WhatsApp</Button>:<Button type="button" onClick={()=>navigator.clipboard?.writeText(mensagem)}>Copiar resumo</Button>}</div>
  <p className="text-xs leading-5 text-muted-foreground">{delivery.short} O preço final é confirmado pela administração. A produção começa após confirmação do pagamento ou sinal.</p>
 </form>;
}
