/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EncomendarRouteImport } from './routes/encomendar'
import { Route as EntregasETermosRouteImport } from './routes/entregas-e-termos'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FiosRouteImport } from './routes/fios'
import { Route as QuadrosDigitaisRouteImport } from './routes/quadros-digitais'
import { Route as ProdutoRouteImport } from './routes/produto'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EncomendarRoute = EncomendarRouteImport.update({
  id: '/encomendar',
  path: '/encomendar',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregasETermosRoute = EntregasETermosRouteImport.update({
  id: '/entregas-e-termos',
  path: '/entregas-e-termos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FiosRoute = FiosRouteImport.update({
  id: '/fios',
  path: '/fios',
  getParentRoute: () => rootRouteImport,
} as any)
const QuadrosDigitaisRoute = QuadrosDigitaisRouteImport.update({
  id: '/quadros-digitais',
  path: '/quadros-digitais',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoRoute = ProdutoRouteImport.update({
  id: '/produto',
  path: '/produto',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/encomendar': typeof EncomendarRoute
  '/entregas-e-termos': typeof EntregasETermosRoute
  '/faq': typeof FaqRoute
  '/fios': typeof FiosRoute
  '/quadros-digitais': typeof QuadrosDigitaisRoute
  '/produto': typeof ProdutoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/encomendar': typeof EncomendarRoute
  '/entregas-e-termos': typeof EntregasETermosRoute
  '/faq': typeof FaqRoute
  '/fios': typeof FiosRoute
  '/quadros-digitais': typeof QuadrosDigitaisRoute
  '/produto': typeof ProdutoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/encomendar': typeof EncomendarRoute
  '/entregas-e-termos': typeof EntregasETermosRoute
  '/faq': typeof FaqRoute
  '/fios': typeof FiosRoute
  '/quadros-digitais': typeof QuadrosDigitaisRoute
  '/produto': typeof ProdutoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/encomendar'
    | '/entregas-e-termos'
    | '/faq'
    | '/fios'
    | '/quadros-digitais'
    | '/produto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/encomendar'
    | '/entregas-e-termos'
    | '/faq'
    | '/fios'
    | '/quadros-digitais'
    | '/produto'
  id:
    | '__root__'
    | '/'
    | '/encomendar'
    | '/entregas-e-termos'
    | '/faq'
    | '/fios'
    | '/quadros-digitais'
    | '/produto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EncomendarRoute: typeof EncomendarRoute
  EntregasETermosRoute: typeof EntregasETermosRoute
  FaqRoute: typeof FaqRoute
  FiosRoute: typeof FiosRoute
  QuadrosDigitaisRoute: typeof QuadrosDigitaisRoute
  ProdutoRoute: typeof ProdutoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encomendar': {
      id: '/encomendar'
      path: '/encomendar'
      fullPath: '/encomendar'
      preLoaderRoute: typeof EncomendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregas-e-termos': {
      id: '/entregas-e-termos'
      path: '/entregas-e-termos'
      fullPath: '/entregas-e-termos'
      preLoaderRoute: typeof EntregasETermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fios': {
      id: '/fios'
      path: '/fios'
      fullPath: '/fios'
      preLoaderRoute: typeof FiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quadros-digitais': {
      id: '/quadros-digitais'
      path: '/quadros-digitais'
      fullPath: '/quadros-digitais'
      preLoaderRoute: typeof QuadrosDigitaisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EncomendarRoute: EncomendarRoute,
  EntregasETermosRoute: EntregasETermosRoute,
  FaqRoute: FaqRoute,
  FiosRoute: FiosRoute,
  QuadrosDigitaisRoute: QuadrosDigitaisRoute,
  ProdutoRoute: ProdutoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}